destination:    ./_site
safe:           true
lsi:            false
include:        [".htaccess"]
exclude:        ["script", "vendor", "Gemfile", "Gemfile.lock", "config.ru", "Procfile", "Rakefile", "readme.md", "scss"]
permalink: /:title
markdown_ext:   markdown,mkd,mkdn,md
